import React, { useState } from 'react';
import {
  FileText,
  ListChecks,
  Lightbulb,
  Code,
  Copy,
  Check,
  Download,
  Clock,
  Sparkles,
  Zap,
  RotateCcw,
  Search,
  BookOpen
} from 'lucide-react';

export default function ResultsView({ data, onReset }) {
  // Default primary tab to 'rawText' (Extracted Text maintaining formatting)
  const [activeTab, setActiveTab] = useState('rawText');
  const [copied, setCopied] = useState(false);
  const [searchQuery, setSearchQuery] = useState('');

  if (!data) return null;

  const {
    fileName,
    fileSize,
    extractionMethod,
    extractedText,
    numPages,
    stats,
    summary,
    keyPoints = [],
    mainIdeas = [],
    improvementSuggestions = [],
    engine,
    errorNote
  } = data;

  const formatFileSize = (bytes) => {
    if (!bytes) return '';
    if (bytes < 1024) return bytes + ' B';
    if (bytes < 1024 * 1024) return (bytes / 1024).toFixed(1) + ' KB';
    return (bytes / (1024 * 1024)).toFixed(2) + ' MB';
  };

  const handleCopyText = () => {
    const textToCopy = activeTab === 'summary' ? summary : extractedText;
    navigator.clipboard.writeText(textToCopy);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadTXT = () => {
    let txtContent = `==================================================\n`;
    txtContent += `DOCUMIND EXTRACTED DOCUMENT REPORT\n`;
    txtContent += `==================================================\n`;
    txtContent += `File Name: ${fileName}\n`;
    txtContent += `File Size: ${formatFileSize(fileSize)}\n`;
    txtContent += `Pages: ${numPages || 1}\n`;
    txtContent += `Word Count: ${stats?.wordCount || 0} words\n`;
    txtContent += `Character Count: ${stats?.characterCount || 0} characters\n`;
    txtContent += `Extraction Method: ${extractionMethod === 'pdf-parse' ? 'PDF Parsing (Formatting Maintained)' : 'Tesseract OCR'}\n`;
    txtContent += `Engine Used: ${engine || 'DocuMind Engine'}\n`;
    txtContent += `==================================================\n\n`;

    txtContent += `--- EXTRACTED TEXT (FORMATTING MAINTAINED) ---\n\n`;
    txtContent += `${extractedText}\n\n`;

    if (summary) {
      txtContent += `==================================================\n`;
      txtContent += `--- EXECUTIVE SUMMARY ---\n`;
      txtContent += `==================================================\n`;
      txtContent += `${summary}\n\n`;
    }

    if (keyPoints.length > 0) {
      txtContent += `--- KEY POINTS & TAKEAWAYS ---\n`;
      keyPoints.forEach((kp, idx) => {
        txtContent += `${idx + 1}. ${kp}\n`;
      });
      txtContent += `\n`;
    }

    if (improvementSuggestions.length > 0) {
      txtContent += `--- DOCUMENT IMPROVEMENT SUGGESTIONS ---\n`;
      improvementSuggestions.forEach((sug, idx) => {
        txtContent += `* ${sug}\n`;
      });
      txtContent += `\n`;
    }

    txtContent += `==================================================\n`;
    txtContent += `Generated by DocuMind Assistant\n`;
    txtContent += `==================================================\n`;

    const blob = new Blob([txtContent], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${fileName.replace(/\.[^/.]+$/, '')}_extracted.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const filteredRawText = searchQuery
    ? extractedText.split('\n').filter((line) => line.toLowerCase().includes(searchQuery.toLowerCase())).join('\n')
    : extractedText;

  const tabs = [
    { id: 'rawText', label: 'Extracted Text (PDF / OCR)', icon: FileText, count: null },
    { id: 'summary', label: 'Executive Summary', icon: BookOpen, count: null },
    { id: 'keyPoints', label: 'Key Points', icon: ListChecks, count: keyPoints.length },
    { id: 'suggestions', label: 'Suggestions', icon: Lightbulb, count: improvementSuggestions.length },
    { id: 'json', label: 'JSON Data', icon: Code, count: null }
  ];

  return (
    <div className="space-y-6 max-w-5xl mx-auto animate-slide-up">
      
      {/* Top Metadata Header */}
      <div className="bg-white border border-slate-200 rounded-3xl p-6 shadow-card-soft space-y-4">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div className="flex items-center space-x-4">
            <div className="w-12 h-12 rounded-2xl bg-emerald-100 border border-emerald-300 flex items-center justify-center text-emerald-700 shrink-0">
              <FileText className="w-6 h-6" />
            </div>
            <div>
              <div className="flex items-center space-x-2">
                <h2 className="text-base font-extrabold text-slate-900 truncate max-w-md">{fileName}</h2>
                <span className="text-[10px] font-extrabold px-2.5 py-0.5 rounded-full bg-emerald-100 text-emerald-800 border border-emerald-300 uppercase">
                  {extractionMethod === 'pdf-parse' ? 'PDF Parsed' : 'Tesseract OCR'}
                </span>
              </div>
              <div className="flex items-center space-x-3 text-xs text-slate-500 mt-1">
                <span>{formatFileSize(fileSize)}</span>
                <span>•</span>
                <span>{stats?.wordCount || 0} words</span>
                <span>•</span>
                <span>{stats?.characterCount || 0} characters</span>
                <span>•</span>
                <span>{numPages || 1} {numPages === 1 ? 'page' : 'pages'}</span>
              </div>
            </div>
          </div>

          {/* Action Toolbar */}
          <div className="flex items-center space-x-2.5">
            <button
              onClick={handleCopyText}
              className="flex items-center space-x-1.5 px-4 py-2.5 text-xs font-bold rounded-xl bg-slate-100 hover:bg-slate-200 text-slate-800 border border-slate-300 transition-colors"
            >
              {copied ? <Check className="w-4 h-4 text-emerald-600" /> : <Copy className="w-4 h-4 text-slate-600" />}
              <span>{copied ? 'Copied' : 'Copy Text'}</span>
            </button>

            <button
              onClick={handleDownloadTXT}
              className="flex items-center space-x-1.5 px-4 py-2.5 text-xs font-bold rounded-xl bg-[#22c55e] hover:bg-[#16a34a] text-slate-950 transition-colors shadow-md shadow-emerald-500/20"
            >
              <Download className="w-4 h-4" />
              <span>Download .TXT</span>
            </button>

            <button
              onClick={onReset}
              className="p-2.5 rounded-xl bg-slate-100 hover:bg-slate-200 text-slate-600 hover:text-slate-900 border border-slate-300 transition-colors"
              title="Upload New Document"
            >
              <RotateCcw className="w-4 h-4" />
            </button>
          </div>
        </div>

        {errorNote && (
          <div className="p-3.5 bg-amber-50 border border-amber-200 rounded-2xl text-xs text-amber-800 flex items-center space-x-2">
            <Sparkles className="w-4 h-4 text-amber-600 shrink-0" />
            <span>{errorNote}</span>
          </div>
        )}
      </div>

      {/* Main Content Container */}
      <div className="bg-white border border-slate-200/90 rounded-3xl overflow-hidden shadow-card-soft">
        
        {/* Navigation Tabs */}
        <div className="flex items-center space-x-1.5 p-2.5 bg-slate-50 border-b border-slate-200 overflow-x-auto">
          {tabs.map((tab) => {
            const Icon = tab.icon;
            const isActive = activeTab === tab.id;
            return (
              <button
                key={tab.id}
                onClick={() => setActiveTab(tab.id)}
                className={`flex items-center space-x-2 px-4 py-2.5 rounded-2xl text-xs font-bold whitespace-nowrap transition-all ${
                  isActive
                    ? 'bg-[#22c55e] text-slate-950 shadow-md shadow-emerald-500/20'
                    : 'text-slate-600 hover:text-slate-900 hover:bg-slate-200/60'
                }`}
              >
                <Icon className="w-4 h-4" />
                <span>{tab.label}</span>
                {tab.count !== null && (
                  <span
                    className={`text-[10px] px-2 py-0.2 rounded-full font-extrabold ${
                      isActive ? 'bg-slate-950 text-white' : 'bg-slate-200 text-slate-700'
                    }`}
                  >
                    {tab.count}
                  </span>
                )}
              </button>
            );
          })}
        </div>

        {/* Tab Content Display Area */}
        <div className="p-7">
          
          {/* TAB 1: EXTRACTED TEXT (PDF Parsing / Tesseract OCR) */}
          {activeTab === 'rawText' && (
            <div className="space-y-4 animate-fade-in">
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-slate-100 pb-3">
                <div>
                  <h3 className="text-sm font-extrabold text-slate-900 flex items-center space-x-2">
                    <FileText className="w-4.5 h-4.5 text-emerald-600" />
                    <span>Extracted Text (Formatting Maintained)</span>
                  </h3>
                  <p className="text-xs text-slate-500 mt-0.5">
                    Extracted via {extractionMethod === 'pdf-parse' ? 'PDF Parsing (preserving layout)' : 'Tesseract Optical Character Recognition (OCR)'}
                  </p>
                </div>
                <div className="relative w-full sm:w-64">
                  <Search className="w-4 h-4 text-slate-400 absolute left-3 top-2.5" />
                  <input
                    type="text"
                    value={searchQuery}
                    onChange={(e) => setSearchQuery(e.target.value)}
                    placeholder="Search in text..."
                    className="w-full pl-9 pr-3.5 py-1.5 bg-slate-50 border border-slate-200 rounded-xl text-xs text-slate-900 placeholder-slate-400 focus:outline-none focus:border-emerald-500"
                  />
                </div>
              </div>

              {/* Formatting Preserved Box */}
              <div className="p-5 bg-slate-50 rounded-2xl border border-slate-200 min-h-[250px] max-h-[500px] overflow-y-auto font-mono text-xs text-slate-800 whitespace-pre-wrap leading-relaxed">
                {filteredRawText || <span className="text-slate-400 italic">No text matching search query.</span>}
              </div>
            </div>
          )}

          {/* TAB 2: EXECUTIVE SUMMARY */}
          {activeTab === 'summary' && (
            <div className="space-y-4 animate-fade-in">
              <div className="flex items-center justify-between border-b border-slate-100 pb-3">
                <h3 className="text-sm font-extrabold text-slate-900 flex items-center space-x-2">
                  <Sparkles className="w-4.5 h-4.5 text-emerald-600" />
                  <span>Executive Summary</span>
                </h3>
                <span className="text-xs text-slate-400 font-mono font-semibold">
                  {summary ? summary.split(/\s+/).length : 0} words
                </span>
              </div>
              <div className="prose prose-slate max-w-none text-slate-700 text-sm leading-relaxed whitespace-pre-line font-sans">
                {summary}
              </div>
            </div>
          )}

          {/* TAB 3: KEY POINTS */}
          {activeTab === 'keyPoints' && (
            <div className="space-y-4 animate-fade-in">
              <h3 className="text-sm font-extrabold text-slate-900 flex items-center space-x-2 border-b border-slate-100 pb-3">
                <ListChecks className="w-4.5 h-4.5 text-emerald-600" />
                <span>Key Points & Main Takeaways</span>
              </h3>
              
              {keyPoints.length > 0 ? (
                <ul className="space-y-3">
                  {keyPoints.map((point, idx) => (
                    <li
                      key={idx}
                      className="p-4 rounded-2xl bg-slate-50 border border-slate-200 flex items-start space-x-3.5 text-xs text-slate-800 leading-relaxed"
                    >
                      <span className="w-6 h-6 rounded-xl bg-emerald-100 text-emerald-800 font-bold text-xs flex items-center justify-center shrink-0 mt-0.5">
                        {idx + 1}
                      </span>
                      <span className="pt-0.5">{point}</span>
                    </li>
                  ))}
                </ul>
              ) : (
                <p className="text-xs text-slate-400 italic">No key points extracted.</p>
              )}
            </div>
          )}

          {/* TAB 4: IMPROVEMENT SUGGESTIONS */}
          {activeTab === 'suggestions' && (
            <div className="space-y-4 animate-fade-in">
              <h3 className="text-sm font-extrabold text-slate-900 flex items-center space-x-2 border-b border-slate-100 pb-3">
                <Lightbulb className="w-4.5 h-4.5 text-amber-500" />
                <span>Document Improvement Suggestions</span>
              </h3>
              
              {improvementSuggestions.length > 0 ? (
                <div className="grid grid-cols-1 gap-3.5">
                  {improvementSuggestions.map((suggestion, idx) => (
                    <div
                      key={idx}
                      className="p-4.5 rounded-2xl bg-amber-50/70 border border-amber-200/80 flex items-start space-x-3.5 text-xs text-amber-950 leading-relaxed"
                    >
                      <Lightbulb className="w-4.5 h-4.5 text-amber-600 shrink-0 mt-0.5" />
                      <div>
                        <span className="font-bold text-amber-900">Recommendation {idx + 1}: </span>
                        <span>{suggestion}</span>
                      </div>
                    </div>
                  ))}
                </div>
              ) : (
                <p className="text-xs text-slate-400 italic">No improvement suggestions derived.</p>
              )}
            </div>
          )}

          {/* TAB 5: JSON DATA */}
          {activeTab === 'json' && (
            <div className="space-y-4 animate-fade-in">
              <h3 className="text-sm font-extrabold text-slate-900 flex items-center space-x-2 border-b border-slate-100 pb-3">
                <Code className="w-4.5 h-4.5 text-blue-600" />
                <span>Raw Response JSON Payload</span>
              </h3>
              <div className="p-5 bg-slate-900 rounded-2xl border border-slate-800 max-h-96 overflow-y-auto font-mono text-[11px] text-emerald-400 whitespace-pre-wrap">
                {JSON.stringify(data, null, 2)}
              </div>
            </div>
          )}

        </div>
      </div>
    </div>
  );
}
